export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const LIMPIAR_STATE = 'LIMPIAR_STATE';



export const FORMULARIO_OPERACION = 'FORMULARIO_OPERACION';
export const OBTENER_OPERACIONES = 'OBTENER_OPERACIONES';
export const AGREGAR_OPERACION = 'AGREGAR_OPERACION';
export const OPERACION_ERROR = 'OPERACION_ERROR';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const OPERACION_ACTUAL = 'OPERACION_ACTUAL';
export const ELIMINAR_OPERACION = 'ELIMINAR_OPERACION';


export const OBTENER_USUARIO = 'OBTENER_USUARIO';