export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION'

export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const OBTENER_OPERACIONES = 'OBTENER_OPERACIONES';
export const AGREGAR_OPERACION = 'AGREGAR_OPERACION';
export const OPERACION_EXITOSA = 'OPERACION_EXITOSA';
export const OPERACION_ERROR = 'OPERACION_ERROR';
export const OPERACION_ACTUAL = 'OPERACION_ACTUAL';
export const ELIMINAR_OPERACION = 'ELIMINAR_OPERACION';
export const ACTUALIZAR_OPERACION = 'ACTUALIZAR_OPERACION';
export const TOTAL_INGRESOS = 'TOTAL_INGRESOS';
export const TOTAL_EGRESOS = 'TOTAL_EGRESOS';
export const CALCULAR_BALANCE = 'CALCULAR_BALANCE';
export const OPERACIONES_CATEGORIAS = 'OPERACIONES_CATEGORIAS';